// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RelationLink } from "./RelationLink";
import type { SelectOption } from "./SelectOption";

export type Task = { id: string, name: string, due_date: Date, status: SelectOption, class: Array<RelationLink>, type_: Array<SelectOption>, extra_props: object, };
